//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoekenApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoekenGenres
    {
        public int Id { get; set; }
        public Nullable<int> BoekId { get; set; }
        public int GenreId { get; set; }
    
        public virtual Boeken Boeken { get; set; }
        public virtual Genres Genres { get; set; }
    }
}
